version: "3.8"
services:
  ianz1:
    image: ianz
    build:
      context: ./
      dockerfile: ianz/Dockerfile
      args:
        - ianz_version=1.0-SNAPSHOT
    ports:
      - 9001:9000
    volumes:
      - ./ianz/examples/ex1:/ianz/indicators
  ianz2:
    image: ianz
    build:
      context: ./
      dockerfile: ianz/Dockerfile
      args:
        - ianz_version=1.0-SNAPSHOT
    ports:
      - 9002:9000
    volumes:
      - ./ianz/examples/ex2:/ianz/indicators